version: '3'
services:
  postgres:
    image: postgres:14.4
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ww360
    volumes:
      - postgresdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  postgresdata:
