FROM node:18.13.0-alpine
ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV
RUN apk add --no-cache git maven curl ca-certificates
WORKDIR /app
COPY ./client ./client
COPY ./server ./server
COPY ./shared ./shared
RUN update-ca-certificates
WORKDIR /app/server
CMD npm run start:prod
